# Generated by Django 4.2.5 on 2026-01-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
