# Generated by Django 4.2.5 on 2026-01-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5, verbose_name='有効期限'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='カード名義'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='カード番号'),
        ),
    ]
