# Generated by Django 4.2.5 on 2026-01-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_card_expiry_order_card_name_order_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True, verbose_name='プロモーションコード')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='割引額')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済み')),
            ],
        ),
    ]
