# Generated by Django 4.2.5 on 2026-08-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotioncode',
            options={'verbose_name_plural': 'プロモーションコード'},
        ),
    ]
