# Generated by Django 4.2.5 on 2026-08-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_promotioncode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_name',
            field=models.CharField(max_length=100, verbose_name='カード名義'),
        ),
    ]
