# Generated by Django 4.2.5 on 2026-08-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_card_name_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_expiry',
            field=models.CharField(max_length=5, verbose_name='有効期限'),
        ),
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=models.CharField(max_length=16, verbose_name='カード番号'),
        ),
    ]
