# Generated by Django 4.2.5 on 2026-10-03 02:48

from django.db import migrations, models


def mark_existing_orders_as_ordered(apps, schema_editor):
    Order = apps.get_model('product', 'Order')
    Order.objects.exclude(status='ordered').update(status='ordered')


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_email_required'),
    ]

    operations = [
        migrations.RunPython(
            mark_existing_orders_as_ordered,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', '注文受付済み')], default='ordered', max_length=10),
        ),
    ]
